###################  spring配置  ###################
spring:
    datasource:
        name: crawler
        url: jdbc:mysql://101.132.145.106:3306/crawler
        username: mysql
        password: k899k899
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:com.qsy.dao.mappers/*.xml
  type-aliases-package: com.qsy.pojo

# Mapper
mapper:
  mappers: com.qsy.dao
  not-empty: false
  identity: MYSQL
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

##########################################################
###################  开发环境的profile  ###################
##########################################################

server:
  port: 8081

swagger:
  groupName: manger
  basePackage: com.qsy.manager.controller

logging:
   level:
      com.googlecode.jsonrpc4j: debug


